//! Mixer parameter registry — definitions, formatting, and lookup for all
//! mixer-visible parameters on the Integra-7.

use std::fmt::Write;

/// How a parameter value should be displayed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ParamFormat {
    /// Display value as-is.
    Raw,
    /// Display as value minus center (e.g. pan 64 -> "0", 0 -> "-64", 127 -> "+63").
    SignedCenter(i32),
    /// Index into a static name array.
    Named(&'static [&'static str]),
    /// Boolean: 0=OFF, 1=ON.
    OnOff,
}

/// Logical grouping for a parameter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ParamGroup {
    /// Per-part parameter (part index 0-15).
    Part(u8),
    /// Master output.
    Master,
    /// External input.
    Ext,
    /// Chorus effect.
    Chorus,
    /// Reverb effect.
    Reverb,
    /// Global / top-level.
    Global,
}

/// A single parameter definition.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParamDef {
    /// Dot-separated identifier, e.g. `"part.0.level"`.
    pub id: &'static str,
    /// Human-readable display name.
    pub name: &'static str,
    /// Which group this parameter belongs to.
    pub group: ParamGroup,
    /// Minimum raw value (inclusive).
    pub min: i32,
    /// Maximum raw value (inclusive).
    pub max: i32,
    /// Default raw value.
    pub default: i32,
    /// Display format.
    pub format: ParamFormat,
}

/// Format a raw parameter value according to the parameter's [`ParamFormat`].
///
/// Returns the formatted string. Out-of-range named indices fall back to the
/// raw numeric representation.
pub fn format_value(def: &ParamDef, value: i32) -> String {
    match &def.format {
        ParamFormat::Raw => value.to_string(),
        ParamFormat::SignedCenter(center) => {
            let offset = value - center;
            if offset > 0 {
                let mut s = String::new();
                let _ = write!(s, "+{offset}");
                s
            } else {
                offset.to_string()
            }
        }
        ParamFormat::Named(names) => {
            let idx = value as usize;
            if idx < names.len() {
                names[idx].to_string()
            } else {
                value.to_string()
            }
        }
        ParamFormat::OnOff => {
            if value == 0 {
                "OFF".to_string()
            } else {
                "ON".to_string()
            }
        }
    }
}

/// Generate all mixer parameter definitions.
///
/// This includes per-part parameters (16 parts x 7 params each), master,
/// external input, chorus, reverb, and the solo-part selector — 124 total.
pub fn mixer_params() -> Vec<ParamDef> {
    // We know the exact count: 16*7 + 1 + 2 + 4 + 4 + 1 = 124
    let mut params = Vec::with_capacity(124);

    static OUTPUT_ASSIGN_NAMES: &[&str] =
        &["A", "B", "C", "D", "1", "2", "3", "4", "5", "6", "7", "8"];
    static CHANNEL_NAMES: &[&str] = &[
        "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16",
    ];

    // We need &'static str ids, so we use a table of pre-built strings.
    // For 16 parts x 7 params we use `const` arrays generated by a macro.
    macro_rules! part_ids {
        ($prefix:expr, $suffix:expr) => {
            [
                concat!($prefix, "0.", $suffix),
                concat!($prefix, "1.", $suffix),
                concat!($prefix, "2.", $suffix),
                concat!($prefix, "3.", $suffix),
                concat!($prefix, "4.", $suffix),
                concat!($prefix, "5.", $suffix),
                concat!($prefix, "6.", $suffix),
                concat!($prefix, "7.", $suffix),
                concat!($prefix, "8.", $suffix),
                concat!($prefix, "9.", $suffix),
                concat!($prefix, "10.", $suffix),
                concat!($prefix, "11.", $suffix),
                concat!($prefix, "12.", $suffix),
                concat!($prefix, "13.", $suffix),
                concat!($prefix, "14.", $suffix),
                concat!($prefix, "15.", $suffix),
            ]
        };
    }

    static LEVEL_IDS: [&str; 16] = part_ids!("part.", "level");
    static PAN_IDS: [&str; 16] = part_ids!("part.", "pan");
    static MUTE_IDS: [&str; 16] = part_ids!("part.", "mute");
    static CHORUS_SEND_IDS: [&str; 16] = part_ids!("part.", "chorus_send");
    static REVERB_SEND_IDS: [&str; 16] = part_ids!("part.", "reverb_send");
    static OUTPUT_ASSIGN_IDS: [&str; 16] = part_ids!("part.", "output_assign");
    static RECEIVE_CHANNEL_IDS: [&str; 16] = part_ids!("part.", "receive_channel");

    for i in 0u8..16 {
        let idx = i as usize;
        params.push(ParamDef {
            id: LEVEL_IDS[idx],
            name: "Level",
            group: ParamGroup::Part(i),
            min: 0,
            max: 127,
            default: 100,
            format: ParamFormat::Raw,
        });
        params.push(ParamDef {
            id: PAN_IDS[idx],
            name: "Pan",
            group: ParamGroup::Part(i),
            min: 0,
            max: 127,
            default: 64,
            format: ParamFormat::SignedCenter(64),
        });
        params.push(ParamDef {
            id: MUTE_IDS[idx],
            name: "Mute",
            group: ParamGroup::Part(i),
            min: 0,
            max: 1,
            default: 0,
            format: ParamFormat::OnOff,
        });
        params.push(ParamDef {
            id: CHORUS_SEND_IDS[idx],
            name: "Chorus Send",
            group: ParamGroup::Part(i),
            min: 0,
            max: 127,
            default: 0,
            format: ParamFormat::Raw,
        });
        params.push(ParamDef {
            id: REVERB_SEND_IDS[idx],
            name: "Reverb Send",
            group: ParamGroup::Part(i),
            min: 0,
            max: 127,
            default: 0,
            format: ParamFormat::Raw,
        });
        params.push(ParamDef {
            id: OUTPUT_ASSIGN_IDS[idx],
            name: "Output Assign",
            group: ParamGroup::Part(i),
            min: 0,
            max: 11,
            default: 0,
            format: ParamFormat::Named(OUTPUT_ASSIGN_NAMES),
        });
        params.push(ParamDef {
            id: RECEIVE_CHANNEL_IDS[idx],
            name: "Receive Channel",
            group: ParamGroup::Part(i),
            min: 0,
            max: 15,
            default: i as i32,
            format: ParamFormat::Named(CHANNEL_NAMES),
        });
    }

    // Master
    params.push(ParamDef {
        id: "master.level",
        name: "Master Level",
        group: ParamGroup::Master,
        min: 0,
        max: 127,
        default: 100,
        format: ParamFormat::Raw,
    });

    // Ext
    params.push(ParamDef {
        id: "ext.level",
        name: "Ext Level",
        group: ParamGroup::Ext,
        min: 0,
        max: 127,
        default: 100,
        format: ParamFormat::Raw,
    });
    params.push(ParamDef {
        id: "ext.mute",
        name: "Ext Mute",
        group: ParamGroup::Ext,
        min: 0,
        max: 1,
        default: 0,
        format: ParamFormat::OnOff,
    });

    // Chorus
    static CHORUS_TYPE_NAMES: &[&str] = &["Chorus", "Delay", "GM2 Chorus", "Off"];
    static CHORUS_OUTPUT_NAMES: &[&str] = &["MAIN", "REV", "MAIN+REV"];

    params.push(ParamDef {
        id: "chorus.enabled",
        name: "Chorus",
        group: ParamGroup::Chorus,
        min: 0,
        max: 1,
        default: 1,
        format: ParamFormat::OnOff,
    });
    params.push(ParamDef {
        id: "chorus.type",
        name: "Chorus Type",
        group: ParamGroup::Chorus,
        min: 0,
        max: 3,
        default: 0,
        format: ParamFormat::Named(CHORUS_TYPE_NAMES),
    });
    params.push(ParamDef {
        id: "chorus.level",
        name: "Chorus Level",
        group: ParamGroup::Chorus,
        min: 0,
        max: 127,
        default: 0,
        format: ParamFormat::Raw,
    });
    params.push(ParamDef {
        id: "chorus.output",
        name: "Chorus Output",
        group: ParamGroup::Chorus,
        min: 0,
        max: 2,
        default: 0,
        format: ParamFormat::Named(CHORUS_OUTPUT_NAMES),
    });

    // Reverb
    static REVERB_TYPE_NAMES: &[&str] = &[
        "Room1",
        "Room2",
        "Hall1",
        "Hall2",
        "Plate",
        "GM2 Reverb",
        "Off",
    ];
    static REVERB_OUTPUT_NAMES: &[&str] = &["A", "B", "C", "D"];

    params.push(ParamDef {
        id: "reverb.enabled",
        name: "Reverb",
        group: ParamGroup::Reverb,
        min: 0,
        max: 1,
        default: 1,
        format: ParamFormat::OnOff,
    });
    params.push(ParamDef {
        id: "reverb.type",
        name: "Reverb Type",
        group: ParamGroup::Reverb,
        min: 0,
        max: 6,
        default: 0,
        format: ParamFormat::Named(REVERB_TYPE_NAMES),
    });
    params.push(ParamDef {
        id: "reverb.level",
        name: "Reverb Level",
        group: ParamGroup::Reverb,
        min: 0,
        max: 127,
        default: 0,
        format: ParamFormat::Raw,
    });
    params.push(ParamDef {
        id: "reverb.output",
        name: "Reverb Output",
        group: ParamGroup::Reverb,
        min: 0,
        max: 3,
        default: 0,
        format: ParamFormat::Named(REVERB_OUTPUT_NAMES),
    });

    // Solo part
    params.push(ParamDef {
        id: "solo_part",
        name: "Solo Part",
        group: ParamGroup::Global,
        min: 0,
        max: 16,
        default: 0,
        format: ParamFormat::Raw,
    });

    params
}

/// Look up a parameter definition by its string id.
pub fn lookup<'a>(params: &'a [ParamDef], id: &str) -> Option<&'a ParamDef> {
    params.iter().find(|p| p.id == id)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mixer_param_count() {
        let params = mixer_params();
        // 16 parts * 7 params + 1 master + 2 ext + 4 chorus + 4 reverb + 1 solo = 124
        assert_eq!(params.len(), 124);
    }

    #[test]
    fn lookup_part_level() {
        let params = mixer_params();
        let def = lookup(&params, "part.0.level").expect("part.0.level should exist");
        assert_eq!(def.min, 0);
        assert_eq!(def.max, 127);
        assert_eq!(def.default, 100);
        assert_eq!(def.group, ParamGroup::Part(0));
    }

    #[test]
    fn format_pan_center() {
        let params = mixer_params();
        let def = lookup(&params, "part.0.pan").unwrap();
        assert_eq!(format_value(def, 64), "0");
    }

    #[test]
    fn format_on_off() {
        let params = mixer_params();
        let def = lookup(&params, "part.0.mute").unwrap();
        assert_eq!(format_value(def, 0), "OFF");
        assert_eq!(format_value(def, 1), "ON");
    }

    #[test]
    fn format_named() {
        let params = mixer_params();
        let def = lookup(&params, "part.0.output_assign").unwrap();
        assert_eq!(format_value(def, 0), "A");
        assert_eq!(format_value(def, 3), "D");
    }
}
