//! Build script: generates `factory_catalog.rs` from `docs/sounds/*.json`.

use std::collections::{BTreeMap, HashMap};
use std::fs;
use std::io::Write;
use std::path::Path;

#[derive(serde::Deserialize)]
struct SoundEntry {
    name: String,
    msb: u8,
    lsb: u8,
    pc: u8,
    #[serde(default)]
    category: Option<String>,
}

/// Load the category name → numeric value mapping from `docs/sounds/categories.json`.
fn load_category_map(sounds_dir: &Path) -> HashMap<String, u8> {
    let cat_path = sounds_dir.join("categories.json");
    println!("cargo::rerun-if-changed={}", cat_path.display());

    let content = fs::read_to_string(&cat_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", cat_path.display()));
    let raw: HashMap<String, String> = serde_json::from_str(&content)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", cat_path.display()));

    let mut map: HashMap<String, u8> = raw
        .into_iter()
        .map(|(k, v)| {
            let num: u8 = k
                .parse()
                .unwrap_or_else(|_| panic!("invalid category key: {k}"));
            (v, num)
        })
        .collect();

    // Aliases from the sound list PDF (different spelling).
    map.insert("Drum".to_string(), 46);
    map
}

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let sounds_dir = Path::new(&manifest_dir).join("../../docs/sounds");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("factory_catalog_data.rs");

    let cat_map = load_category_map(&sounds_dir);

    // Collect all entries grouped by (msb, lsb).
    // (pc, name, category_value)
    type BankEntries = Vec<(u8, String, u8)>;
    let mut banks: BTreeMap<(u8, u8), BankEntries> = BTreeMap::new();

    let json_files = [
        "sn-acoustic-preset.json",
        "sn-synth-preset.json",
        "sn-drum-preset.json",
        "pcm-synth-preset.json",
        "pcm-drum-preset.json",
        "gm2.json",
        "exsn.json",
        "expcm.json",
    ];

    for filename in &json_files {
        let path = sounds_dir.join(filename);
        if !path.exists() {
            continue;
        }
        println!("cargo::rerun-if-changed={}", path.display());

        let content = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
        let entries: Vec<SoundEntry> = serde_json::from_str(&content)
            .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()));

        for entry in entries {
            let cat_val = entry
                .category
                .as_deref()
                .and_then(|c| cat_map.get(c).copied())
                .unwrap_or(0);

            // PC is 1-indexed in JSON, convert to 0-indexed for MIDI.
            let pc = entry.pc.saturating_sub(1);

            banks
                .entry((entry.msb, entry.lsb))
                .or_default()
                .push((pc, entry.name, cat_val));
        }
    }

    // Sort entries within each bank by PC.
    for tones in banks.values_mut() {
        tones.sort_by_key(|t| t.0);
    }

    // Generate Rust source.
    let mut out = fs::File::create(&out_path).expect("failed to create output file");

    writeln!(out, "// Generated by build.rs — do not edit.").unwrap();
    writeln!(out).unwrap();

    // Emit one const array per bank.
    for ((msb, lsb), tones) in &banks {
        let ident = format!("BANK_{msb}_{lsb}");
        writeln!(out, "const {ident}: &[FactoryTone] = &[",).unwrap();
        for (pc, name, cat) in tones {
            // Escape any quotes in names.
            let escaped = name.replace('\\', "\\\\").replace('"', "\\\"");
            writeln!(
                out,
                "    FactoryTone {{ msb: {msb}, lsb: {lsb}, pc: {pc}, name: \"{escaped}\", category: {cat} }},",
            )
            .unwrap();
        }
        writeln!(out, "];").unwrap();
        writeln!(out).unwrap();
    }

    // Emit the lookup function.
    writeln!(
        out,
        "/// Look up factory tones for a given bank (MSB, LSB)."
    )
    .unwrap();
    writeln!(out, "///").unwrap();
    writeln!(
        out,
        "/// Returns a static slice of tones, or an empty slice for user/unknown banks."
    )
    .unwrap();
    writeln!(
        out,
        "pub fn factory_tones(msb: u8, lsb: u8) -> &'static [FactoryTone] {{"
    )
    .unwrap();
    writeln!(out, "    match (msb, lsb) {{").unwrap();
    for (msb, lsb) in banks.keys() {
        let ident = format!("BANK_{msb}_{lsb}");
        writeln!(out, "        ({msb}, {lsb}) => {ident},").unwrap();
    }
    writeln!(out, "        _ => &[],").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();

    // Total count for documentation.
    let total: usize = banks.values().map(|v| v.len()).sum();
    eprintln!(
        "factory_catalog: generated {} tones across {} banks",
        total,
        banks.len()
    );

    // -----------------------------------------------------------------------
    // Generate tone_category_data.rs (for svd.rs)
    // -----------------------------------------------------------------------

    let cat_data_path = Path::new(&out_dir).join("tone_category_data.rs");
    let mut cat_out = fs::File::create(&cat_data_path).expect("failed to create category output");

    writeln!(cat_out, "// Generated by build.rs — do not edit.").unwrap();
    writeln!(cat_out).unwrap();

    // Re-read the categories JSON for the forward mapping (value → name).
    let cat_json_path = sounds_dir.join("categories.json");
    let cat_content = fs::read_to_string(&cat_json_path).unwrap();
    let cat_entries: BTreeMap<u8, String> = {
        let raw: BTreeMap<String, String> = serde_json::from_str(&cat_content).unwrap();
        raw.into_iter()
            .map(|(k, v)| (k.parse::<u8>().unwrap(), v))
            .collect()
    };

    writeln!(
        cat_out,
        "/// Return the human-readable name for a tone category value."
    )
    .unwrap();
    writeln!(cat_out, "///").unwrap();
    writeln!(cat_out, "/// Generated from `docs/sounds/categories.json`.").unwrap();
    writeln!(
        cat_out,
        "pub fn tone_category_name(value: u8) -> Option<&'static str> {{"
    )
    .unwrap();
    writeln!(cat_out, "    match value {{").unwrap();
    for (val, name) in &cat_entries {
        writeln!(cat_out, "        {val} => Some(\"{name}\"),").unwrap();
    }
    writeln!(cat_out, "        _ => None,").unwrap();
    writeln!(cat_out, "    }}").unwrap();
    writeln!(cat_out, "}}").unwrap();
}
