//! Build script: generates `factory_catalog.rs` from `docs/sounds/*.json`.

use std::collections::{BTreeMap, HashMap};
use std::fs;
use std::io::Write;
use std::path::Path;

#[derive(serde::Deserialize)]
struct SoundEntry {
    name: String,
    msb: u8,
    lsb: u8,
    pc: u8,
    #[serde(default)]
    category: Option<String>,
}

/// Reverse mapping from category name → numeric value.
/// Must stay in sync with `tone_category_name()` in `svd.rs`.
fn category_name_to_value() -> HashMap<&'static str, u8> {
    HashMap::from([
        ("No assign", 0),
        ("Ac.Piano", 1),
        ("E.Piano", 5),
        ("Organ", 6),
        ("Other Keyboards", 10),
        ("Accordion/Harmonica", 12),
        ("Bell/Mallet", 14),
        ("Ac.Guitar", 16),
        ("E.Guitar", 17),
        ("Dist.Guitar", 18),
        ("Ac.Bass", 19),
        ("E.Bass", 20),
        ("Synth Bass", 21),
        ("Plucked/Stroke", 22),
        ("Strings", 24),
        ("Brass", 26),
        ("Wind", 28),
        ("Flute", 29),
        ("Sax", 30),
        ("Recorder", 31),
        ("Vox/Choir", 32),
        ("Synth Lead", 34),
        ("Synth Brass", 35),
        ("Synth Pad/Strings", 36),
        ("Synth Bellpad", 37),
        ("Synth PolyKey", 38),
        ("FX", 39),
        ("Synth Seq/Pop", 40),
        ("Phrase", 41),
        ("Pulsating", 42),
        ("Beat&Groove", 43),
        ("Hit", 44),
        ("Sound FX", 45),
        ("Drums", 46),
        ("Percussion", 47),
        ("Combination", 48),
        // Aliases from the sound list PDF (different spelling).
        ("Drum", 46),
    ])
}

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let sounds_dir = Path::new(&manifest_dir).join("../../docs/sounds");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("factory_catalog_data.rs");

    let cat_map = category_name_to_value();

    // Collect all entries grouped by (msb, lsb).
    // (pc, name, category_value)
    type BankEntries = Vec<(u8, String, u8)>;
    let mut banks: BTreeMap<(u8, u8), BankEntries> = BTreeMap::new();

    let json_files = [
        "sn-acoustic-preset.json",
        "sn-synth-preset.json",
        "sn-drum-preset.json",
        "pcm-synth-preset.json",
        "pcm-drum-preset.json",
        "gm2.json",
        "exsn.json",
        "expcm.json",
    ];

    for filename in &json_files {
        let path = sounds_dir.join(filename);
        if !path.exists() {
            continue;
        }
        println!("cargo::rerun-if-changed={}", path.display());

        let content = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
        let entries: Vec<SoundEntry> = serde_json::from_str(&content)
            .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()));

        for entry in entries {
            let cat_val = entry
                .category
                .as_deref()
                .and_then(|c| cat_map.get(c).copied())
                .unwrap_or(0);

            // PC is 1-indexed in JSON, convert to 0-indexed for MIDI.
            let pc = entry.pc.saturating_sub(1);

            banks
                .entry((entry.msb, entry.lsb))
                .or_default()
                .push((pc, entry.name, cat_val));
        }
    }

    // Sort entries within each bank by PC.
    for tones in banks.values_mut() {
        tones.sort_by_key(|t| t.0);
    }

    // Generate Rust source.
    let mut out = fs::File::create(&out_path).expect("failed to create output file");

    writeln!(out, "// Generated by build.rs — do not edit.").unwrap();
    writeln!(out).unwrap();

    // Emit one const array per bank.
    for ((msb, lsb), tones) in &banks {
        let ident = format!("BANK_{msb}_{lsb}");
        writeln!(out, "const {ident}: &[FactoryTone] = &[",).unwrap();
        for (pc, name, cat) in tones {
            // Escape any quotes in names.
            let escaped = name.replace('\\', "\\\\").replace('"', "\\\"");
            writeln!(
                out,
                "    FactoryTone {{ msb: {msb}, lsb: {lsb}, pc: {pc}, name: \"{escaped}\", category: {cat} }},",
            )
            .unwrap();
        }
        writeln!(out, "];").unwrap();
        writeln!(out).unwrap();
    }

    // Emit the lookup function.
    writeln!(
        out,
        "/// Look up factory tones for a given bank (MSB, LSB)."
    )
    .unwrap();
    writeln!(out, "///").unwrap();
    writeln!(
        out,
        "/// Returns a static slice of tones, or an empty slice for user/unknown banks."
    )
    .unwrap();
    writeln!(
        out,
        "pub fn factory_tones(msb: u8, lsb: u8) -> &'static [FactoryTone] {{"
    )
    .unwrap();
    writeln!(out, "    match (msb, lsb) {{").unwrap();
    for (msb, lsb) in banks.keys() {
        let ident = format!("BANK_{msb}_{lsb}");
        writeln!(out, "        ({msb}, {lsb}) => {ident},").unwrap();
    }
    writeln!(out, "        _ => &[],").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();

    // Total count for documentation.
    let total: usize = banks.values().map(|v| v.len()).sum();
    eprintln!(
        "factory_catalog: generated {} tones across {} banks",
        total,
        banks.len()
    );
}
